'use client'

import { useState, useEffect, useRef, Suspense } from 'react'
import { useSearchParams } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import type { ApplicationProfile } from '@/types/database'

type Tool = 'cover_letter' | 'cv_highlights' | 'review' | 'cv_tips' | 'batch'

interface UserProfile {
  full_name: string | null
  target_field: string | null
  region: string | null
}

interface JobData {
  id: string
  title: string
  company: string
  location: string | null
  description: string | null
}

interface BookmarkedJob {
  id: string
  stellenanzeige_id: string
  stellenanzeigen: {
    id: string
    title: string
    company: string
    location: string | null
  } | null
}

const TOOLS: { key: Tool; label: string; icon: string; desc: string }[] = [
  { key: 'cover_letter', label: 'Motivationsschreiben', icon: '✍️', desc: 'Maßgeschneidert für eine konkrete Stelle' },
  { key: 'cv_highlights', label: 'CV-Highlights', icon: '📌', desc: 'Relevante Erfahrungen stellenspezifisch framen' },
  { key: 'review', label: 'Prüfen & Optimieren', icon: '🔍', desc: 'Bestehendes Schreiben analysieren' },
  { key: 'batch', label: 'Batch-Bewerbungen', icon: '⚡', desc: '2–6 Stellen auf einmal generieren' },
  { key: 'cv_tips', label: 'CV-Tipps', icon: '📄', desc: 'Quereinstieg im Lebenslauf positiv framen' },
]

function buildJobText(job: JobData): string {
  const lines: string[] = [`Stelle: ${job.title}`, `Firma: ${job.company}`]
  if (job.location) lines.push(`Ort: ${job.location}`)
  if (job.description) lines.push(`\nStellenbeschreibung:\n${job.description.slice(0, 600)}`)
  return lines.join('\n')
}

function AIPageContent() {
  const searchParams = useSearchParams()
  const jobId = searchParams.get('jobId')

  const [tier, setTier] = useState<number | null>(null)
  const [profile, setProfile] = useState<UserProfile>({ full_name: null, target_field: null, region: null })
  const [applicationProfile, setApplicationProfile] = useState<ApplicationProfile | null>(null)
  const [job, setJob] = useState<JobData | null>(null)
  const [activeTool, setActiveTool] = useState<Tool>('cover_letter')
  const [jobText, setJobText] = useState('')
  const [strengths, setStrengths] = useState('')
  const [hook, setHook] = useState('')
  const [reviewText, setReviewText] = useState('')
  const [cvBackground, setCvBackground] = useState('')
  const [result, setResult] = useState('')
  const [loading, setLoading] = useState(false)
  const [bookmarks, setBookmarks] = useState<BookmarkedJob[]>([])
  const [selectedJobs, setSelectedJobs] = useState<Set<string>>(new Set())
  const [batchResults, setBatchResults] = useState<Record<string, string>>({})
  const [batchProgress, setBatchProgress] = useState(0)
  const resultRef = useRef<HTMLTextAreaElement>(null)
  const autoGeneratedRef = useRef<Set<string>>(new Set())
  const supabase = createClient()

  // Load profile + bookmarks
  useEffect(() => {
    async function loadProfile() {
      let { data, error } = await supabase
        .from('profiles')
        .select('tier, full_name, target_field, region, application_profile')
        .single()

      // Graceful fallback if application_profile column doesn't exist yet (SQL migration pending)
      if (error && (error.code === '42703' || error.message?.includes('application_profile'))) {
        const retry = await supabase
          .from('profiles')
          .select('tier, full_name, target_field, region')
          .single()
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        data = retry.data as any
      }

      setTier(data?.tier ?? 1)
      if (data) {
        setProfile({ full_name: data.full_name, target_field: data.target_field, region: data.region })
        setApplicationProfile((data.application_profile as ApplicationProfile) ?? null)
      }
    }
    loadProfile()
    fetch('/api/user/bookmarks').then(r => r.json()).then(d => setBookmarks(d.bookmarks ?? []))
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // Load job when jobId present
  useEffect(() => {
    if (!jobId) return
    supabase
      .from('stellenanzeigen')
      .select('id, title, company, location, description')
      .eq('id', jobId)
      .single()
      .then(({ data }) => {
        if (data) setJob(data as JobData)
      })
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [jobId])

  // Auto-generate cover letter when job + applicationProfile loaded
  useEffect(() => {
    if (!job || !applicationProfile || loading || result) return
    if (activeTool !== 'cover_letter') return
    const key = `cover_letter:${job.id}`
    if (autoGeneratedRef.current.has(key)) return
    autoGeneratedRef.current.add(key)
    const text = buildJobText(job)
    setJobText(text)
    generate('cover_letter', text)
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [job, applicationProfile])

  // Auto-generate CV highlights when switching to cv_highlights tab with job + profile
  useEffect(() => {
    if (!job || !applicationProfile || loading || result) return
    if (activeTool !== 'cv_highlights') return
    const key = `cv_highlights:${job.id}`
    if (autoGeneratedRef.current.has(key)) return
    autoGeneratedRef.current.add(key)
    generate('cv_highlights', buildJobText(job))
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [job, applicationProfile, activeTool])

  async function generate(type: string, inputText: string, opts?: object) {
    setResult('')
    setLoading(true)
    try {
      const res = await fetch('/api/ai/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ type, jobText: inputText, userProfile: profile, options: opts }),
      })
      if (!res.ok) {
        const err = await res.json()
        setResult(`Fehler: ${err.error}`)
        return
      }
      const reader = res.body!.getReader()
      const decoder = new TextDecoder()
      let text = ''
      while (true) {
        const { done, value } = await reader.read()
        if (done) break
        const chunk = decoder.decode(value)
        const lines = chunk.split('\n')
        for (const line of lines) {
          if (line.startsWith('data: ')) {
            const data = line.slice(6)
            if (data === '[DONE]') break
            try {
              const parsed = JSON.parse(data)
              if (parsed.text) {
                text += parsed.text
                setResult(text)
              }
            } catch {}
          }
        }
      }
    } finally {
      setLoading(false)
    }
  }

  async function generateBatch() {
    const jobs = bookmarks.filter(b => selectedJobs.has(b.stellenanzeige_id))
    if (jobs.length === 0) return
    setBatchResults({})
    setBatchProgress(0)
    setLoading(true)
    for (let i = 0; i < jobs.length; i++) {
      const bJob = jobs[i]
      const jobInfo = bJob.stellenanzeigen
        ? `${bJob.stellenanzeigen.title} bei ${bJob.stellenanzeigen.company}${bJob.stellenanzeigen.location ? ` in ${bJob.stellenanzeigen.location}` : ''}`
        : bJob.stellenanzeige_id
      let text = ''
      const res = await fetch('/api/ai/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ type: 'cover_letter', jobText: jobInfo, userProfile: profile }),
      })
      if (res.ok) {
        const reader = res.body!.getReader()
        const decoder = new TextDecoder()
        while (true) {
          const { done, value } = await reader.read()
          if (done) break
          const chunk = decoder.decode(value)
          for (const line of chunk.split('\n')) {
            if (line.startsWith('data: ')) {
              const data = line.slice(6)
              if (data === '[DONE]') break
              try { const p = JSON.parse(data); if (p.text) text += p.text } catch {}
            }
          }
        }
      }
      setBatchResults(prev => ({ ...prev, [bJob.stellenanzeige_id]: text }))
      setBatchProgress(i + 1)
    }
    setLoading(false)
  }

  function copyResult(text: string) {
    navigator.clipboard.writeText(text)
  }

  function downloadResult(text: string, filename: string) {
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
  }

  if (tier === null) return <div style={{ padding: 40, color: '#9CA3AF' }}>Lädt…</div>

  if (tier < 3) {
    return (
      <div style={{ padding: '32px 40px', maxWidth: 720, margin: '0 auto' }}>
        <h1 style={{ fontSize: 22, fontWeight: 700, color: '#1A2332', marginBottom: 24 }}>KI-Bewerbungsassistent</h1>
        <div style={{
          background: 'linear-gradient(135deg, #EEF2FF, #F5F3FF)',
          border: '1px solid #C7D2FE',
          borderRadius: 16,
          padding: '40px 36px',
          textAlign: 'center',
        }}>
          <div style={{ fontSize: 48, marginBottom: 16 }}>🤖</div>
          <h2 style={{ fontSize: 20, fontWeight: 700, color: '#1E1B4B', marginBottom: 12 }}>
            6 Bewerbungen in 8 Minuten
          </h2>
          <div style={{ fontSize: 14, color: '#4338CA', lineHeight: 1.7, marginBottom: 24, maxWidth: 440, margin: '0 auto 24px' }}>
            Claude generiert maßgeschneiderte Motivationsschreiben für deine Wunschstellen –
            in der Zeit, die du früher für eine einzige Bewerbung gebraucht hast.
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, maxWidth: 440, margin: '0 auto 28px', textAlign: 'left' }}>
            {[
              { icon: '✍️', text: 'Motivationsschreiben auf Knopfdruck' },
              { icon: '⚡', text: 'Batch: bis zu 6 Stellen gleichzeitig' },
              { icon: '🔍', text: 'Bewerb-Review mit Before/After' },
              { icon: '📌', text: 'CV-Highlights stellenspezifisch' },
            ].map(f => (
              <div key={f.text} style={{ display: 'flex', alignItems: 'flex-start', gap: 10, padding: '12px 14px', background: '#fff', borderRadius: 10, fontSize: 13, color: '#374151' }}>
                <span style={{ fontSize: 18 }}>{f.icon}</span>
                {f.text}
              </div>
            ))}
          </div>
          <div style={{ fontSize: 22, fontWeight: 700, color: '#4F46E5', marginBottom: 12 }}>CHF 79 / Monat</div>
          <div style={{ fontSize: 12, color: '#6B7280', marginBottom: 20 }}>Inkl. allem aus Pro (CHF 29/mo)</div>
          <button style={{
            padding: '13px 36px',
            background: 'linear-gradient(90deg, #6366F1, #8B5CF6)',
            color: '#fff',
            border: 'none',
            borderRadius: 10,
            fontSize: 15,
            fontWeight: 700,
            cursor: 'pointer',
          }}>
            AI-Paket aktivieren
          </button>
        </div>
      </div>
    )
  }

  const showSideBySide = !!job && (!!result || loading) && (activeTool === 'cover_letter' || activeTool === 'cv_highlights')
  const showAmberBanner = !applicationProfile && (activeTool === 'cover_letter' || activeTool === 'cv_highlights')

  const ResultSection = ({ marginTop = 0 }: { marginTop?: number }) => (
    <div style={{ marginTop }}>
      {loading && !result && (
        <div style={{ padding: '20px', background: '#EEF2FF', borderRadius: 10, fontSize: 13, color: '#4F46E5', display: 'flex', alignItems: 'center', gap: 12 }}>
          <span style={{ fontSize: 20 }}>⏳</span>
          Claude generiert deinen Text…
        </div>
      )}
      {result && (
        <>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 }}>
            <div style={{ fontSize: 14, fontWeight: 700, color: '#1A2332' }}>Ergebnis</div>
            <div style={{ display: 'flex', gap: 8 }}>
              <button onClick={() => copyResult(result)} style={{ padding: '6px 14px', border: '1px solid #E5E0D8', borderRadius: 6, fontSize: 12, cursor: 'pointer', background: '#fff' }}>
                Kopieren
              </button>
              <button onClick={() => downloadResult(result, 'bewerbung.txt')} style={{ padding: '6px 14px', border: '1px solid #E5E0D8', borderRadius: 6, fontSize: 12, cursor: 'pointer', background: '#fff' }}>
                Als .txt herunterladen
              </button>
            </div>
          </div>
          <textarea
            ref={resultRef}
            value={result}
            onChange={e => setResult(e.target.value)}
            rows={showSideBySide ? 22 : 16}
            style={{
              width: '100%',
              padding: '16px',
              border: '1.5px solid #C7D2FE',
              borderRadius: 10,
              fontSize: 13,
              fontFamily: 'inherit',
              resize: 'vertical',
              outline: 'none',
              lineHeight: 1.7,
              background: '#FAFAFA',
            }}
          />
        </>
      )}
    </div>
  )

  return (
    <div style={{ padding: '32px 40px', maxWidth: 1100, margin: '0 auto' }}>
      <div style={{ marginBottom: 20 }}>
        <h1 style={{ fontSize: 22, fontWeight: 700, color: '#1A2332', marginBottom: 4 }}>KI-Bewerbungsassistent</h1>
        <p style={{ fontSize: 13, color: '#6B7280' }}>Powered by Claude (claude-sonnet-4-6)</p>
      </div>

      {/* Job Card */}
      {job && (
        <div style={{
          background: '#fff',
          border: '1.5px solid #C7D2FE',
          borderRadius: 10,
          padding: '14px 18px',
          marginBottom: 14,
          display: 'flex',
          gap: 12,
          alignItems: 'flex-start',
        }}>
          <div style={{ fontSize: 20 }}>📋</div>
          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={{ fontSize: 15, fontWeight: 700, color: '#1A2332', marginBottom: 2 }}>{job.title}</div>
            <div style={{ fontSize: 13, color: '#6B7280', marginBottom: job.description ? 6 : 0 }}>
              {job.company}{job.location ? ` · ${job.location}` : ''}
            </div>
            {job.description && (
              <div style={{ fontSize: 12, color: '#9CA3AF', lineHeight: 1.5 }}>
                {job.description.slice(0, 250)}{job.description.length > 250 ? '…' : ''}
              </div>
            )}
          </div>
        </div>
      )}

      {/* Amber banner: missing application profile */}
      {showAmberBanner && (
        <div style={{
          background: '#FFFBEB',
          border: '1px solid #FDE68A',
          borderRadius: 8,
          padding: '11px 16px',
          marginBottom: 14,
          fontSize: 13,
          color: '#92400E',
          lineHeight: 1.5,
        }}>
          💡 <strong>Tipp:</strong> Fülle dein{' '}
          <a href="/dashboard/profil" style={{ color: '#E67E22', fontWeight: 600, textDecoration: 'none' }}>
            Bewerbungsprofil
          </a>{' '}
          aus — dann schreibt Claude mit deinem echten Werdegang viel bessere, personalisierte Schreiben.
        </div>
      )}

      {/* Tool Tabs */}
      <div style={{ display: 'flex', gap: 10, marginBottom: 24, flexWrap: 'wrap' }}>
        {TOOLS.map(t => (
          <button
            key={t.key}
            onClick={() => { setActiveTool(t.key as Tool); setResult(''); setBatchResults({}) }}
            style={{
              padding: '9px 16px',
              border: `1.5px solid ${activeTool === t.key ? '#6366F1' : '#E5E0D8'}`,
              borderRadius: 10,
              background: activeTool === t.key ? '#EEF2FF' : '#fff',
              color: activeTool === t.key ? '#4F46E5' : '#374151',
              fontSize: 13,
              fontWeight: activeTool === t.key ? 700 : 500,
              cursor: 'pointer',
            }}
          >
            {t.icon} {t.label}
          </button>
        ))}
      </div>

      {/* Main layout: side-by-side when job + result, else vertical */}
      <div style={{
        display: 'flex',
        flexDirection: showSideBySide ? 'row' : 'column',
        gap: showSideBySide ? 24 : 0,
        alignItems: 'flex-start',
      }}>
        {/* Left / full-width: tool controls */}
        <div style={{ flex: showSideBySide ? '0 0 38%' : 1 }}>

          {/* ── Cover Letter ── */}
          {activeTool === 'cover_letter' && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
              {!job && (
                <div>
                  <label style={{ display: 'block', fontSize: 13, fontWeight: 600, color: '#374151', marginBottom: 6 }}>
                    Stellenbeschreibung oder URL (einfügen)
                  </label>
                  <textarea
                    value={jobText}
                    onChange={e => setJobText(e.target.value)}
                    rows={6}
                    placeholder="Stelle hier den Stelleninserat-Text oder eine kurze Beschreibung ein…"
                    style={{ width: '100%', padding: '12px', border: '1.5px solid #E5E0D8', borderRadius: 8, fontSize: 13, resize: 'vertical', outline: 'none', fontFamily: 'inherit' }}
                  />
                </div>
              )}
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
                <div>
                  <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: '#6B7280', marginBottom: 4 }}>Besondere Stärken (optional)</label>
                  <input
                    value={strengths}
                    onChange={e => setStrengths(e.target.value)}
                    placeholder="z.B. Kundenkontakt, Teamführung"
                    style={{ width: '100%', padding: '8px 12px', border: '1.5px solid #E5E0D8', borderRadius: 8, fontSize: 13, outline: 'none' }}
                  />
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: '#6B7280', marginBottom: 4 }}>Persönlicher Aufhänger (optional)</label>
                  <input
                    value={hook}
                    onChange={e => setHook(e.target.value)}
                    placeholder="z.B. 10 Jahre Erfahrung in…"
                    style={{ width: '100%', padding: '8px 12px', border: '1.5px solid #E5E0D8', borderRadius: 8, fontSize: 13, outline: 'none' }}
                  />
                </div>
              </div>
              <button
                onClick={() => generate('cover_letter', job ? buildJobText(job) : jobText, { strengths, hook })}
                disabled={loading || (!job && !jobText.trim())}
                style={{
                  padding: '11px 24px',
                  background: loading || (!job && !jobText.trim()) ? '#9CA3AF' : 'linear-gradient(90deg, #6366F1, #8B5CF6)',
                  color: '#fff',
                  border: 'none',
                  borderRadius: 8,
                  fontSize: 14,
                  fontWeight: 600,
                  cursor: loading || (!job && !jobText.trim()) ? 'not-allowed' : 'pointer',
                  alignSelf: 'flex-start',
                }}
              >
                {loading ? 'Generiert…' : result ? '↻ Neu generieren' : '✍️ Motivationsschreiben generieren'}
              </button>
            </div>
          )}

          {/* ── CV-Highlights ── */}
          {activeTool === 'cv_highlights' && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
              {!job ? (
                <div style={{
                  padding: '20px 24px',
                  background: '#F9FAFB',
                  border: '1px solid #E5E7EB',
                  borderRadius: 10,
                  fontSize: 13,
                  color: '#6B7280',
                  lineHeight: 1.6,
                }}>
                  📌 Öffne einen Job und klicke{' '}
                  <strong>"KI-Bewerbung"</strong>{' '}
                  für stellenspezifische CV-Highlights.
                  <br />
                  Oder wechsle zu einem Job aus deinen{' '}
                  <a href="/dashboard/jobs" style={{ color: '#E67E22', textDecoration: 'none', fontWeight: 600 }}>
                    gespeicherten Stellen
                  </a>.
                </div>
              ) : (
                <>
                  {!applicationProfile && (
                    <div style={{
                      padding: '10px 14px',
                      background: '#FFFBEB',
                      border: '1px solid #FDE68A',
                      borderRadius: 8,
                      fontSize: 12,
                      color: '#92400E',
                    }}>
                      Ohne Bewerbungsprofil sind die Highlights weniger personalisiert.{' '}
                      <a href="/dashboard/profil" style={{ color: '#E67E22', fontWeight: 600, textDecoration: 'none' }}>Profil ausfüllen →</a>
                    </div>
                  )}
                  <button
                    onClick={() => generate('cv_highlights', buildJobText(job))}
                    disabled={loading}
                    style={{
                      padding: '11px 24px',
                      background: loading ? '#9CA3AF' : 'linear-gradient(90deg, #6366F1, #8B5CF6)',
                      color: '#fff',
                      border: 'none',
                      borderRadius: 8,
                      fontSize: 14,
                      fontWeight: 600,
                      cursor: loading ? 'not-allowed' : 'pointer',
                      alignSelf: 'flex-start',
                    }}
                  >
                    {loading ? 'Generiert…' : result ? '↻ Neue Highlights' : '📌 CV-Highlights generieren'}
                  </button>
                </>
              )}
            </div>
          )}

          {/* ── Review ── */}
          {activeTool === 'review' && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
              <div>
                <label style={{ display: 'block', fontSize: 13, fontWeight: 600, color: '#374151', marginBottom: 6 }}>
                  Dein bestehendes Motivationsschreiben
                </label>
                <textarea
                  value={reviewText}
                  onChange={e => setReviewText(e.target.value)}
                  rows={8}
                  placeholder="Füge dein Motivationsschreiben hier ein…"
                  style={{ width: '100%', padding: '12px', border: '1.5px solid #E5E0D8', borderRadius: 8, fontSize: 13, resize: 'vertical', outline: 'none', fontFamily: 'inherit' }}
                />
              </div>
              <button
                onClick={() => generate('review', reviewText)}
                disabled={loading || !reviewText.trim()}
                style={{
                  padding: '11px 24px',
                  background: loading || !reviewText.trim() ? '#9CA3AF' : 'linear-gradient(90deg, #6366F1, #8B5CF6)',
                  color: '#fff',
                  border: 'none',
                  borderRadius: 8,
                  fontSize: 14,
                  fontWeight: 600,
                  cursor: loading || !reviewText.trim() ? 'not-allowed' : 'pointer',
                  alignSelf: 'flex-start',
                }}
              >
                {loading ? 'Analysiert…' : '🔍 Bewerbung analysieren'}
              </button>
            </div>
          )}

          {/* ── CV-Tips ── */}
          {activeTool === 'cv_tips' && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
              <div>
                <label style={{ display: 'block', fontSize: 13, fontWeight: 600, color: '#374151', marginBottom: 6 }}>
                  Bisheriger Werdegang (kurz beschreiben)
                </label>
                <textarea
                  value={cvBackground}
                  onChange={e => setCvBackground(e.target.value)}
                  rows={5}
                  placeholder="z.B. 8 Jahre Projektmanager in der Pharmaindustrie, davor Studium Wirtschaft…"
                  style={{ width: '100%', padding: '12px', border: '1.5px solid #E5E0D8', borderRadius: 8, fontSize: 13, resize: 'vertical', outline: 'none', fontFamily: 'inherit' }}
                />
              </div>
              <button
                onClick={() => generate('cv_tips', cvBackground)}
                disabled={loading || !cvBackground.trim()}
                style={{
                  padding: '11px 24px',
                  background: loading || !cvBackground.trim() ? '#9CA3AF' : 'linear-gradient(90deg, #6366F1, #8B5CF6)',
                  color: '#fff',
                  border: 'none',
                  borderRadius: 8,
                  fontSize: 14,
                  fontWeight: 600,
                  cursor: loading || !cvBackground.trim() ? 'not-allowed' : 'pointer',
                  alignSelf: 'flex-start',
                }}
              >
                {loading ? 'Analysiert…' : '📄 CV-Tipps generieren'}
              </button>
            </div>
          )}

          {/* ── Batch ── */}
          {activeTool === 'batch' && (
            <div>
              <div style={{ fontSize: 13, color: '#6B7280', marginBottom: 16 }}>
                Wähle 2–6 gespeicherte Jobs für die Batch-Generierung:
              </div>
              {bookmarks.length === 0 ? (
                <div style={{ padding: '24px', background: '#F9FAFB', borderRadius: 10, textAlign: 'center', color: '#9CA3AF', fontSize: 14 }}>
                  Keine gespeicherten Jobs. Erst Jobs bookmarken in der Jobs-Seite.
                </div>
              ) : (
                <>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 8, marginBottom: 16 }}>
                    {bookmarks.slice(0, 10).map(b => {
                      const bJobData = b.stellenanzeigen
                      const checked = selectedJobs.has(b.stellenanzeige_id)
                      return (
                        <label key={b.stellenanzeige_id} style={{
                          display: 'flex',
                          alignItems: 'center',
                          gap: 12,
                          padding: '12px 16px',
                          background: checked ? '#EEF2FF' : '#fff',
                          border: `1.5px solid ${checked ? '#6366F1' : '#E5E0D8'}`,
                          borderRadius: 8,
                          cursor: 'pointer',
                        }}>
                          <input
                            type="checkbox"
                            checked={checked}
                            onChange={e => {
                              const next = new Set(selectedJobs)
                              if (e.target.checked) {
                                if (next.size < 6) next.add(b.stellenanzeige_id)
                              } else {
                                next.delete(b.stellenanzeige_id)
                              }
                              setSelectedJobs(next)
                            }}
                            style={{ width: 16, height: 16, accentColor: '#6366F1' }}
                          />
                          <div>
                            <div style={{ fontSize: 13, fontWeight: 600, color: '#1A2332' }}>{bJobData?.title ?? 'Job'}</div>
                            <div style={{ fontSize: 12, color: '#6B7280' }}>{bJobData?.company}{bJobData?.location ? ` · ${bJobData.location}` : ''}</div>
                          </div>
                        </label>
                      )
                    })}
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 16, marginBottom: 20 }}>
                    <button
                      onClick={generateBatch}
                      disabled={loading || selectedJobs.size < 2}
                      style={{
                        padding: '11px 24px',
                        background: loading || selectedJobs.size < 2 ? '#9CA3AF' : 'linear-gradient(90deg, #6366F1, #8B5CF6)',
                        color: '#fff',
                        border: 'none',
                        borderRadius: 8,
                        fontSize: 14,
                        fontWeight: 600,
                        cursor: loading || selectedJobs.size < 2 ? 'not-allowed' : 'pointer',
                      }}
                    >
                      {loading ? `Generiert ${batchProgress}/${selectedJobs.size}…` : `⚡ ${selectedJobs.size} Bewerbungen generieren`}
                    </button>
                    {selectedJobs.size >= 2 && !loading && (
                      <div style={{ fontSize: 12, color: '#6B7280' }}>
                        ~{selectedJobs.size * 1.5} Min.
                        <span style={{ marginLeft: 8, color: '#10B981', fontWeight: 600 }}>
                          (statt ~{selectedJobs.size * 10}h manuell)
                        </span>
                      </div>
                    )}
                  </div>
                  {Object.entries(batchResults).map(([jobId2, text]) => {
                    const bookmark = bookmarks.find(b => b.stellenanzeige_id === jobId2)
                    const jobTitle = bookmark?.stellenanzeigen?.title ?? jobId2
                    return (
                      <div key={jobId2} style={{ marginBottom: 20 }}>
                        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 }}>
                          <div style={{ fontSize: 14, fontWeight: 700, color: '#1A2332' }}>{jobTitle}</div>
                          <div style={{ display: 'flex', gap: 8 }}>
                            <button onClick={() => copyResult(text)} style={{ padding: '5px 12px', border: '1px solid #E5E0D8', borderRadius: 6, fontSize: 12, cursor: 'pointer', background: '#fff' }}>
                              Kopieren
                            </button>
                            <button onClick={() => downloadResult(text, `bewerbung-${jobId2.slice(0, 8)}.txt`)} style={{ padding: '5px 12px', border: '1px solid #E5E0D8', borderRadius: 6, fontSize: 12, cursor: 'pointer', background: '#fff' }}>
                              Download
                            </button>
                          </div>
                        </div>
                        <textarea
                          defaultValue={text}
                          rows={8}
                          style={{ width: '100%', padding: '12px', border: '1.5px solid #E5E0D8', borderRadius: 8, fontSize: 13, fontFamily: 'inherit', resize: 'vertical' }}
                        />
                      </div>
                    )
                  })}
                </>
              )}
            </div>
          )}
        </div>

        {/* Right: Result (side-by-side mode) */}
        {showSideBySide && (
          <div style={{ flex: 1 }}>
            <ResultSection />
          </div>
        )}
      </div>

      {/* Result below (vertical layout) */}
      {!showSideBySide && activeTool !== 'batch' && (result || loading) && (
        <ResultSection marginTop={24} />
      )}
    </div>
  )
}

export default function AIPage() {
  return (
    <Suspense fallback={<div style={{ padding: 40, color: '#9CA3AF' }}>Lädt…</div>}>
      <AIPageContent />
    </Suspense>
  )
}
